# -*- coding: utf-8 -*-
"""VisualisationCharts

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qa_ei_yDix9IvI6bXfLSh8zF7r_nq02j
"""

from google.colab import files
uploaded = files.upload()

# ------------------------------
# IMPORTS
# ------------------------------
import pandas as pd
import matplotlib.pyplot as plt

# ------------------------------
# LOAD THE DATA (UPLOAD FILES IN COLAB)
# ------------------------------
ingredients = pd.read_csv("ingredients.csv")
interactions = pd.read_csv("interactions.csv")
recipes = pd.read_csv("recipe.csv")
steps = pd.read_csv("steps.csv")
users = pd.read_csv("users.csv")

# ------------------------------
# BASIC CLEANING
# ------------------------------
interactions['rating'] = pd.to_numeric(interactions['rating'], errors='coerce')

# Ensure view/like/cook_attempt counts
view_counts = interactions[interactions['type']=="view"]
like_counts = interactions[interactions['type']=="like"]

# ------------------------------
# 1. MOST COMMON INGREDIENTS
# ------------------------------
top_ingredients = ingredients['ingredient_name'].value_counts().head(10)

plt.figure()
top_ingredients.plot(kind='bar')
plt.title("Top 10 Most Common Ingredients")
plt.xlabel("Ingredient")
plt.ylabel("Count")
plt.show()

# ------------------------------
# 2. AVERAGE PREPARATION TIME
# ------------------------------
if "prep_time" in recipes.columns:
    avg_prep = recipes["prep_time"].mean()
else:
    recipes.rename(columns={"prep_time_mins":"prep_time"}, inplace=True)
    avg_prep = recipes["prep_time"].mean()

plt.figure()
plt.bar(["Average Prep Time"], [avg_prep])
plt.title("Average Preparation Time (Minutes)")
plt.ylabel("Minutes")
plt.show()

# ------------------------------
# 3. DIFFICULTY DISTRIBUTION
# ------------------------------
plt.figure()
recipes['difficulty'].value_counts().plot(kind='bar')
plt.title("Difficulty Distribution")
plt.xlabel("Difficulty Level")
plt.ylabel("Number of Recipes")
plt.show()

# ------------------------------
# 4. CORRELATION: PREP TIME VS LIKES
# ------------------------------
likes_per_recipe = like_counts.groupby("recipe_id").size().reset_index(name="likes")

df_corr = recipes.merge(likes_per_recipe, on="recipe_id", how="left")
df_corr["likes"] = df_corr["likes"].fillna(0)

plt.figure()
plt.scatter(df_corr["prep_time"], df_corr["likes"])
plt.title("Prep Time vs Likes")
plt.xlabel("Prep Time (mins)")
plt.ylabel("Likes")
plt.show()

# ------------------------------
# 5. MOST VIEWED RECIPES
# ------------------------------
top_views = view_counts.groupby("recipe_id").size().sort_values(ascending=False).head(10)

plt.figure()
top_views.plot(kind='bar')
plt.title("Top 10 Most Viewed Recipes")
plt.xlabel("Recipe ID")
plt.ylabel("Views")
plt.show()

# ------------------------------
# 6. INGREDIENTS ASSOCIATED WITH HIGH LIKES
# ------------------------------
merged_ing = ingredients.merge(likes_per_recipe, on="recipe_id", how="left")
merged_ing["likes"] = merged_ing["likes"].fillna(0)

top_liked_ingredients = merged_ing.groupby("ingredient_name")["likes"].mean().sort_values(ascending=False).head(10)

plt.figure()
top_liked_ingredients.plot(kind='bar')
plt.title("Top Ingredients With Highest Average Likes")
plt.xlabel("Ingredient")
plt.ylabel("Average Likes")
plt.show()

# ------------------------------
# 7. RECIPE LENGTH (NUMBER OF STEPS)
# ------------------------------
step_counts = steps.groupby("recipe_id").size().sort_values(ascending=False).head(10)

plt.figure()
step_counts.plot(kind="bar")
plt.title("Recipes With Most Steps")
plt.xlabel("Recipe ID")
plt.ylabel("Number of Steps")
plt.show()

# ------------------------------
# 8. ACTIVE USERS (MOST INTERACTIONS)
# ------------------------------
top_users = interactions["user_id"].value_counts().head(10)

plt.figure()
top_users.plot(kind="bar")
plt.title("Top 10 Most Active Users")
plt.xlabel("User ID")
plt.ylabel("Interactions")
plt.show()

# ------------------------------
# 9. TOP RATED RECIPES (USING RATING)
# ------------------------------
rated = interactions.dropna(subset=["rating"])
top_rated = rated.groupby("recipe_id")["rating"].mean().sort_values(ascending=False).head(10)

plt.figure()
top_rated.plot(kind="bar")
plt.title("Top 10 Highest Rated Recipes")
plt.xlabel("Recipe ID")
plt.ylabel("Average Rating")
plt.show()

# ------------------------------
# 10. RECIPES WITH MOST TOTAL ENGAGEMENT (views + likes + cook_attempt)
# ------------------------------
engagement = interactions.groupby("recipe_id").size().sort_values(ascending=False).head(10)

plt.figure()
engagement.plot(kind="bar")
plt.title("Most Engaging Recipes (All Interaction Types)")
plt.xlabel("Recipe ID")
plt.ylabel("Engagement Count")
plt.show()

# ------------------------------
# IMPORTS
# ------------------------------
import pandas as pd
import matplotlib.pyplot as plt

# Upload already done
ingredients = pd.read_csv("ingredients.csv")
interactions = pd.read_csv("interactions.csv")
recipes = pd.read_csv("recipe.csv")
steps = pd.read_csv("steps.csv")
users = pd.read_csv("users.csv")

interactions['rating'] = pd.to_numeric(interactions['rating'], errors='coerce')

# Counting types
view_counts = interactions[interactions['type']=="view"]
like_counts = interactions[interactions['type']=="like"]

# ----------------------------------------------------
# 1. MOST COMMON INGREDIENTS (Horizontal Colorful Bar)
# ----------------------------------------------------
top_ing = ingredients['ingredient_name'].value_counts().head(10)

plt.figure(figsize=(10,6))
top_ing.plot(kind='barh')
plt.title("Top 10 Most Common Ingredients", fontsize=16)
plt.xlabel("Count")
plt.ylabel("Ingredient")
plt.gca().invert_yaxis()
plt.show()

# ----------------------------------------------------
# 2. AVERAGE PREP TIME (Donut Chart)
# ----------------------------------------------------
if "prep_time" in recipes.columns:
    avg_prep = recipes["prep_time"].mean()
else:
    recipes.rename(columns={"prep_time_mins":"prep_time"}, inplace=True)
    avg_prep = recipes["prep_time"].mean()

plt.figure(figsize=(6,6))
sizes = [avg_prep, 60-avg_prep if avg_prep < 60 else 0]
plt.pie(sizes, labels=["Avg Prep Time", ""], startangle=90, wedgeprops={'width':0.4})
plt.title("Average Preparation Time (Donut Chart)", fontsize=16)
plt.show()

# ----------------------------------------------------
# 3. DIFFICULTY DISTRIBUTION (Pie Chart)
# ----------------------------------------------------
plt.figure(figsize=(7,7))
recipes['difficulty'].value_counts().plot(kind="pie", autopct='%1.1f%%')
plt.title("Difficulty Distribution", fontsize=16)
plt.ylabel("")
plt.show()

# ----------------------------------------------------
# 4. PREP TIME VS LIKES (Scatter Plot)
# ----------------------------------------------------
likes_per_recipe = like_counts.groupby("recipe_id").size().reset_index(name="likes")
df_corr = recipes.merge(likes_per_recipe, on="recipe_id", how="left")
df_corr["likes"] = df_corr["likes"].fillna(0)

plt.figure(figsize=(8,6))
plt.scatter(df_corr["prep_time"], df_corr["likes"], s=80)
plt.title("Prep Time vs Likes", fontsize=16)
plt.xlabel("Prep Time (mins)")
plt.ylabel("Likes")
plt.grid(True, linestyle="--", alpha=0.5)
plt.show()

# ----------------------------------------------------
# 5. MOST VIEWED RECIPES (Line Chart)
# ----------------------------------------------------
top_views = view_counts.groupby("recipe_id").size().sort_values(ascending=False).head(10)

plt.figure(figsize=(10,6))
plt.plot(top_views.index, top_views.values, marker="o")
plt.title("Top 10 Most Viewed Recipes", fontsize=16)
plt.xlabel("Recipe ID")
plt.ylabel("Views")
plt.grid(True, linestyle="--", alpha=0.5)
plt.show()

# ----------------------------------------------------
# 6. INGREDIENTS WITH HIGH LIKES (Heatmap-style Bars)
# ----------------------------------------------------
merged_ing = ingredients.merge(likes_per_recipe, on="recipe_id", how="left")
merged_ing["likes"] = merged_ing["likes"].fillna(0)

top_liked_ing = merged_ing.groupby("ingredient_name")["likes"].mean().sort_values(ascending=False).head(10)

plt.figure(figsize=(10,6))
bars = plt.bar(top_liked_ing.index, top_liked_ing.values)
plt.title("Top Ingredients by Average Likes", fontsize=16)
plt.xticks(rotation=45)
plt.ylabel("Avg Likes")

# Color heatmap effect
for bar in bars:
    bar.set_color(plt.cm.viridis(bar.get_height() / max(top_liked_ing.values)))

plt.show()

# ----------------------------------------------------
# 7. RECIPES WITH MOST STEPS (Horizontal Bar)
# ----------------------------------------------------
step_counts = steps.groupby("recipe_id").size().sort_values(ascending=False).head(10)

plt.figure(figsize=(10,6))
step_counts.plot(kind="barh", color="teal")
plt.title("Recipes With Most Steps", fontsize=16)
plt.xlabel("Steps Count")
plt.gca().invert_yaxis()
plt.show()

# ----------------------------------------------------
# 8. MOST ACTIVE USERS (Bubble-Style)
# ----------------------------------------------------
top_users = interactions["user_id"].value_counts().head(10)

plt.figure(figsize=(10,6))
plt.scatter(top_users.index, top_users.values, s=top_users.values*50, alpha=0.6)
plt.title("Most Active Users (Bubble Chart)", fontsize=16)
plt.xlabel("User ID")
plt.ylabel("Interaction Count")
plt.grid(True, linestyle="--", alpha=0.5)
plt.show()

# ----------------------------------------------------
# 9. TOP RATED RECIPES (Horizontal Bar)
# ----------------------------------------------------
rated = interactions.dropna(subset=["rating"])
top_rated = rated.groupby("recipe_id")["rating"].mean().sort_values(ascending=False).head(10)

plt.figure(figsize=(10,6))
top_rated.plot(kind="barh", color="purple")
plt.title("Top Rated Recipes", fontsize=16)
plt.xlabel("Average Rating")
plt.gca().invert_yaxis()
plt.show()

# ----------------------------------------------------
# 10. MOST ENGAGING RECIPES (Bar + Grid)
# ----------------------------------------------------
engagement = interactions.groupby("recipe_id").size().sort_values(ascending=False).head(10)

plt.figure(figsize=(10,6))
plt.bar(engagement.index, engagement.values, color="orange")
plt.title("Most Engaging Recipes", fontsize=16)
plt.xlabel("Recipe ID")
plt.ylabel("Engagement Count")
plt.grid(True, linestyle="--", alpha=0.4)
plt.show()